version: "3.8"

services:
  app:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: npm run dev
    ports:
      - 8080:8080
  server:
    image: maven:3.8.1-openjdk-11-slim
    command: mvn spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/largesse
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SERVER_ADDRESS: 0.0.0.0
    working_dir: /app
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: largesse
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  maven-repo:
